version: '3.8'

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app
    environment:
      - TZ=Asia/Seoul
    networks:
      - fastapi_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - fastapi
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
