services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app
    environment:
      - TZ=Asia/Seoul
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true  # 외부 네트워크 설정
